[platformio]
default_envs = m5stack-core2-server

[env:m5stack-core2-server]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200

lib_deps =
    m5stack/M5Core2@^0.2.0
    h2zero/NimBLE-Arduino

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DDEVICE_ROLE=ROLE_HOST

[env:m5stack-core2-client]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200

lib_deps =
    m5stack/M5Core2@^0.2.0
    h2zero/NimBLE-Arduino

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DDEVICE_ROLE=ROLE_CLIENT